### ISSUE TITLE
called() always fails with td.when().thenCallback()

### ISSUE THREAD

**Issue by albertogasparin** [BaseCase/testdouble-chai#3]
I was wondering why my tests were not passing, and it looks like there is a bug in your plugin. See the sample test below:

``` js
beforeEach(function() {
  this.subject = td.function("dubs");
  this.wrapper = td.function("wrapper");
  td.when(this.wrapper()).thenCallback(true);
});

describe(".called", function() {
  it("passes if the callback testdouble was called", function() {
    this.wrapper(this.subject);
    expect(this.subject).to.have.been.called(); // this fails
    expect(this.subject).to.have.been.calledWith(true); // but this passes
  });
});
```

(Moreover with test double 1.6.0, `npm run test` reports another test failing but I don't know if it's related)

**Comment by BaseCase** [comment]
Thanks for the bug report! I'll take a look at that as soon as I get a chance.

**Comment by BaseCase** [comment]
In reverse order:

Looks like the random 1.6.0 test failure was caused by an internal change in testdouble exposing a flaw in our test suite: we weren't calling `td.reset()` after each test.

The `.thenCallback` issue seems to have been because the `.called` helper was strict about arguments, as is `td.verify`'s default behavior. I relaxed that strictness (since you can use `.calledWith()` in the even that you want to test it was called with exactly zero args) and that seemed to clear it up for me.

@albertogasparin I'll release a new version in a minute here, so please try that and let me know if you're still seeing the issue!

**Comment by albertogasparin** [comment]
Thanks for the quick fix! Works great now. 
Cheers 👍
